trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Config
  displayName: 'Config'
  jobs:
  - job: NodeInstall
    displayName: 'Install Node'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'

- stage: LocalTest
  displayName: 'Local Run Test'
  dependsOn: Config
  jobs:
  - job: LocalRun
    displayName: 'Local Run Test'
    steps:
      - task: BrowserStackConfig@0
        inputs:
            BrowserStackServiceEndPoint: 'BS_Demo_Creds'
      - script: |
          npm install
          npm run bstack-local
        displayName: 'Run local test'
